### ISSUE TITLE
command error

### ISSUE THREAD

**Issue by binggege** [alexjlockwood/ShapeShifter#238]
command： npm run build
node version:  7.7.2
use branch:  master
``` 
ERROR in ./src/styles.scss
Module build failed: Error: Missing binding /Users/yabing.zyb/www/ShapeShifter/node_modules/_node-sass@4.8.3@node-sass/vendor/darwin-x64-51/binding.node
Node Sass could not find a binding for your current environment: OS X 64-bit with Node.js 7.x

Found bindings for the following environments:
  - OS X 64-bit with Node.js 8.x

This usually happens because your environment has changed since running `npm install`.
Run `npm rebuild node-sass --force` to build the binding for your current environment.
    at module.exports (/Users/yabing.zyb/www/ShapeShifter/node_modules/_node-sass@4.8.3@node-sass/lib/binding.js:15:13)
    at Object.<anonymous> (/Users/yabing.zyb/www/ShapeShifter/node_modules/_node-sass@4.8.3@node-sass/lib/index.js:14:35)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/yabing.zyb/www/ShapeShifter/node_modules/_sass-loader@6.0.7@sass-loader/lib/loader.js:3:14)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
ERROR in Module build failed: Error: Missing binding /Users/yabing.zyb/www/ShapeShifter/node_modules/_node-sass@4.8.3@node-sass/vendor/darwin-x64-51/binding.node
Node Sass could not find a binding for your current environment: OS X 64-bit with Node.js 7.x

Found bindings for the following environments:
  - OS X 64-bit with Node.js 8.x

This usually happens because your environment has changed since running `npm install`.
Run `npm rebuild node-sass --force` to build the binding for your current environment.
    at module.exports (/Users/yabing.zyb/www/ShapeShifter/node_modules/_node-sass@4.8.3@node-sass/lib/binding.js:15:13)
    at Object.<anonymous> (/Users/yabing.zyb/www/ShapeShifter/node_modules/_node-sass@4.8.3@node-sass/lib/index.js:14:35)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/yabing.zyb/www/ShapeShifter/node_modules/_sass-loader@6.0.7@sass-loader/lib/loader.js:3:14)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
ERROR in ./src/styles.scss
Module build failed: ModuleBuildError: Module build failed: Error: Missing binding /Users/yabing.zyb/www/ShapeShifter/node_modules/_node-sass@4.8.3@node-sass/vendor/darwin-x64-51/binding.node
Node Sass could not find a binding for your current environment: OS X 64-bit with Node.js 7.x

Found bindings for the following environments:
  - OS X 64-bit with Node.js 8.x

This usually happens because your environment has changed since running `npm install`.
Run `npm rebuild node-sass --force` to build the binding for your current environment.
    at module.exports (/Users/yabing.zyb/www/ShapeShifter/node_modules/_node-sass@4.8.3@node-sass/lib/binding.js:15:13)
    at Object.<anonymous> (/Users/yabing.zyb/www/ShapeShifter/node_modules/_node-sass@4.8.3@node-sass/lib/index.js:14:35)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/yabing.zyb/www/ShapeShifter/node_modules/_sass-loader@6.0.7@sass-loader/lib/loader.js:3:14)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at runLoaders (/Users/yabing.zyb/www/ShapeShifter/node_modules/_webpack@3.11.0@webpack/lib/NormalModule.js:195:19)
    at /Users/yabing.zyb/www/ShapeShifter/node_modules/_loader-runner@2.3.0@loader-runner/lib/LoaderRunner.js:364:11
    at /Users/yabing.zyb/www/ShapeShifter/node_modules/_loader-runner@2.3.0@loader-runner/lib/LoaderRunner.js:170:18
    at loadLoader (/Users/yabing.zyb/www/ShapeShifter/node_modules/_loader-runner@2.3.0@loader-runner/lib/loadLoader.js:27:11)
    at iteratePitchingLoaders (/Users/yabing.zyb/www/ShapeShifter/node_modules/_loader-runner@2.3.0@loader-runner/lib/LoaderRunner.js:169:2)
    at iteratePitchingLoaders (/Users/yabing.zyb/www/ShapeShifter/node_modules/_loader-runner@2.3.0@loader-runner/lib/LoaderRunner.js:165:10)
    at /Users/yabing.zyb/www/ShapeShifter/node_modules/_loader-runner@2.3.0@loader-runner/lib/LoaderRunner.js:173:18
    at loadLoader (/Users/yabing.zyb/www/ShapeShifter/node_modules/_loader-runner@2.3.0@loader-runner/lib/loadLoader.js:36:3)
    at iteratePitchingLoaders (/Users/yabing.zyb/www/ShapeShifter/node_modules/_loader-runner@2.3.0@loader-runner/lib/LoaderRunner.js:169:2)
    at iteratePitchingLoaders (/Users/yabing.zyb/www/ShapeShifter/node_modules/_loader-runner@2.3.0@loader-runner/lib/LoaderRunner.js:165:10)
    at /Users/yabing.zyb/www/ShapeShifter/node_modules/_loader-runner@2.3.0@loader-runner/lib/LoaderRunner.js:173:18
    at loadLoader (/Users/yabing.zyb/www/ShapeShifter/node_modules/_loader-runner@2.3.0@loader-runner/lib/loadLoader.js:36:3)
    at iteratePitchingLoaders (/Users/yabing.zyb/www/ShapeShifter/node_modules/_loader-runner@2.3.0@loader-runner/lib/LoaderRunner.js:169:2)
    at runLoaders (/Users/yabing.zyb/www/ShapeShifter/node_modules/_loader-runner@2.3.0@loader-runner/lib/LoaderRunner.js:362:2)
    at NormalModule.doBuild (/Users/yabing.zyb/www/ShapeShifter/node_modules/_webpack@3.11.0@webpack/lib/NormalModule.js:182:3)
    at NormalModule.build (/Users/yabing.zyb/www/ShapeShifter/node_modules/_webpack@3.11.0@webpack/lib/NormalModule.js:275:15)

npm ERR! Darwin 17.4.0
npm ERR! argv "/Users/yabing.zyb/.nvm/versions/node/v7.7.2/bin/node" "/Users/yabing.zyb/.nvm/versions/node/v7.7.2/bin/npm" "run" "build"
npm ERR! node v7.7.2
npm ERR! npm  v4.1.2
npm ERR! code ELIFECYCLE
npm ERR! shapeshifter@1.0.5 build: `node --max-old-space-size=8192 ./node_modules/.bin/ng build -prod`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the shapeshifter@1.0.5 build script 'node --max-old-space-size=8192 ./node_modules/.bin/ng build -prod'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the shapeshifter package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node --max-old-space-size=8192 ./node_modules/.bin/ng build -prod
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs shapeshifter
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls shapeshifter
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/yabing.zyb/www/ShapeShifter/npm-debug.log
```

**Comment by alexjlockwood** [comment]
Never seen this before...

Did you try running the command that is mentioned in the error message? (`npm rebuild node-sass --force`)

Also, what versions of `node` and `npm` are you using? This is what the output looks like on my machine:

```
$ npm version
{ shapeshifter: '1.0.5',
  npm: '5.8.0',
  ares: '1.13.0',
  cldr: '32.0',
  http_parser: '2.7.0',
  icu: '60.1',
  modules: '59',
  napi: '2',
  nghttp2: '1.29.0',
  node: '9.5.0',
  openssl: '1.0.2n',
  tz: '2017c',
  unicode: '10.0',
  uv: '1.19.1',
  v8: '6.2.414.46-node.18',
  zlib: '1.2.11' }
```

**Comment by binggege** [comment]
```
$ npm version
{ npm: '4.1.2',
  ares: '1.10.1-DEV',
  cldr: '30.0.3',
  http_parser: '2.7.0',
  icu: '58.2',
  modules: '51',
  node: '7.7.2',
  openssl: '1.0.2k',
  tz: '2016j',
  unicode: '9.0',
  uv: '1.11.0',
  v8: '5.5.372.41',
  zlib: '1.2.11' }
```

**Comment by alexjlockwood** [comment]
Yeah, so maybe try upgrading your node to something 8.0 or above? The error message says that your current environment is `OS X 64-bit with Node.js 7.x` but it is looking for `OS X 64-bit with Node.js 8.x`... so seems like upgrading to 8.0 could fix the issue.

**Comment by alexjlockwood** [comment]
`nvm install stable` and then `rm -rf node_modules` and then `npm i` and `npm start` maybe?

**Comment by binggege** [comment]
well done,it's ok now ,thx
