### ISSUE TITLE
There are still errors when I run  npm run build

### ISSUE THREAD

**Issue by binggege** [alexjlockwood/ShapeShifter#240]
node -v:  v8.9.0
branch: master
npm version
```
{ shapeshifter: '1.0.5',
  npm: '5.8.0',
  ares: '1.10.1-DEV',
  cldr: '31.0.1',
  http_parser: '2.7.0',
  icu: '59.1',
  modules: '57',
  nghttp2: '1.25.0',
  node: '8.9.0',
  openssl: '1.0.2l',
  tz: '2017b',
  unicode: '9.0',
  uv: '1.15.0',
  v8: '6.1.534.46',
  zlib: '1.2.11' }
```
error msg ：
```
95% emittingUnhandled rejection Error: ENOENT: no such file or directory, open '/Users/yabing.zyb/www/ShapeShifter/node_modules/_@angular-devkit_build-optimizer@0.3.2@@angular-devkit/package.json'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.readFileSync (fs.js:551:33)
    at LicenseExtractor.readPackageJson (/Users/yabing.zyb/www/ShapeShifter/node_modules/_license-webpack-plugin@1.3.1@license-webpack-plugin/dist/LicenseExtractor.js:126:23)
    at LicenseExtractor.parsePackage (/Users/yabing.zyb/www/ShapeShifter/node_modules/_license-webpack-plugin@1.3.1@license-webpack-plugin/dist/LicenseExtractor.js:23:32)
    at ModuleProcessor.processPackage (/Users/yabing.zyb/www/ShapeShifter/node_modules/_license-webpack-plugin@1.3.1@license-webpack-plugin/dist/ModuleProcessor.js:39:46)
    at ModuleProcessor.processFile (/Users/yabing.zyb/www/ShapeShifter/node_modules/_license-webpack-plugin@1.3.1@license-webpack-plugin/dist/ModuleProcessor.js:36:21)
    at fileCallback (/Users/yabing.zyb/www/ShapeShifter/node_modules/_license-webpack-plugin@1.3.1@license-webpack-plugin/dist/LicenseWebpackPlugin.js:101:61)
    at Array.forEach (<anonymous>)
    at moduleCallback (/Users/yabing.zyb/www/ShapeShifter/node_modules/_license-webpack-plugin@1.3.1@license-webpack-plugin/dist/LicenseWebpackPlugin.js:112:42)
    at /Users/yabing.zyb/www/ShapeShifter/node_modules/_license-webpack-plugin@1.3.1@license-webpack-plugin/dist/LicenseWebpackPlugin.js:120:29
    at Array.forEach (<anonymous>)
    at Compiler.emitCallback (/Users/yabing.zyb/www/ShapeShifter/node_modules/_license-webpack-plugin@1.3.1@license-webpack-plugin/dist/LicenseWebpackPlugin.js:86:32)
    at next (/Users/yabing.zyb/www/ShapeShifter/node_modules/_tapable@0.2.8@tapable/lib/Tapable.js:204:14)
    at /Users/yabing.zyb/www/ShapeShifter/node_modules/_html-webpack-plugin@2.30.1@html-webpack-plugin/index.js:204:9
    at PassThroughHandlerContext.finallyHandler (/Users/yabing.zyb/www/ShapeShifter/node_modules/_bluebird@3.5.1@bluebird/js/release/finally.js:56:23)
    at PassThroughHandlerContext.tryCatcher (/Users/yabing.zyb/www/ShapeShifter/node_modules/_bluebird@3.5.1@bluebird/js/release/util.js:16:23)
```

**Comment by alexjlockwood** [comment]
Did you re-run npm install after switching to master?

**Comment by alexjlockwood** [comment]
The next branch introduces a few new dependencies, so you have to re-run that command each time you switch to and from that branch.

**Comment by binggege** [comment]
The  follow is my step:
1.  git checkout master
2. rm -rf node_modules
3. npm i
4. npm run build

**Comment by alexjlockwood** [comment]
You shouldn't have to force delete the node_modules (npm i should be enough). But glad the problem is resolved now!
