### ISSUE TITLE
SyntaxError: Unexpected token

### ISSUE THREAD

**Issue by IcyHeartBX** [alexjlockwood/ShapeShifter#62]
$ ng server
C:\Users\Administrator\AppData\Roaming\npm\node_modules\@angular\cli\models\conf                                     ig\config.js:16
    constructor(_configPath, schema, configJson, fallbacks = []) {
                                                           ^

SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\Users\Administrator\AppData\Roaming\npm\node_modul                                     es\@angular\cli\models\config.js:3:18)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)

**Comment by alexjlockwood** [comment]
Thanks for reporting!

First, could you try `ng serve` instead of `ng server`?

Second, could you execute `ng version` and copy/paste the output in a comment? Make sure your node version is up-to-date (for example, mine outputs `node: 7.3.0`).

**Comment by alexjlockwood** [comment]
Please reopen if you are still having the issue, but I suspect your node is probably not up to date. Make sure you have the latest version! :)
